  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
   - password=root
resources: 
  - MysqlDeploy.yml
  - WordPress.yml
  - Provision.yml
  - rbac.yml
  - StorageClass.yml